---
# defaults file for cloudera-postgressql-10
postgres_create_users:
        - {role: scm , password: password}
        - {role: amon , password: password}
        - {role: rman , password: password}
        - {role: hue , password: password}
        - {role: hive , password: password}
        - {role: registry , password: password}
        - {role: streamsmsgmgr , password: password}

postgres_create_db:
        - {db_name: scm , owner: scm , encoding: UTF8}
        - {db_name: amon , owner: amon , encoding: UTF8}
        - {db_name: rman , owner: rman , encoding: UTF8}
        - {db_name: hue , owner: hue , encoding: UTF8}
        - {db_name: metastore , owner: hive , encoding: UTF8}
        - {db_name: registry , owner: registry , encoding: UTF8}
        - {db_name: streamsmsgmgr , owner: streamsmsgmgr , encoding: UTF8}

postgres_configuration:
     postgresql_configuration_file_path: /var/lib/pgsql/10/data/postgresql.conf
     pg_hba_configuration_file_path: /var/lib/pgsql/10/data/pg_hba.conf
     postgresql_parameters:
          - {parameter: max_connections , value: 1000} # Need to have at least 1000 connections per DB
          - {parameter: wal_buffers , value: 8MB}
          - {parameter: shared_buffers , value: 256MB}
          - {parameter: checkpoint_completion_target , value: 0.9}
          - {parameter: max_wal_size , value: 768MB}
          - {parameter: min_wal_size , value: 80MB}
          - {parameter: listen_addresses , value: "'*'"}