- hosts: kmanager
  vars_files:
    - ./cloudera_environment.yml
    - ./defaults/cloudera-managment-info.yml
  tasks:

  - name: test - check connectivity to cloudera API
    get_url:
        url: http://{{ cloudera_managment_server.hostname }}.{{ domain }}:7180/api/v33/clusters/{{ cloudera_ingestion_cluster_name }}
        dest: /tmp/
        mode: 0777
        force: yes
        url_username: "{{ cloudera_web_ui.cloudera_username }}"
        url_password: "{{ cloudera_web_ui.cloudera_password }}"
        validate_certs: no
    register: msg
    ignore_errors: true


  - name: Test - failed result message
    fail:
     msg: "One or more  Cloudera API parameters is wrong. Check main parameters such as cluster-name,username under /opt/solution/deployment/bigdata_cloudera_deployment/defaults/cloudera-managment-info.yml"
    when: msg.uid == 0


  - name: delete existing cloudera-api secret
    shell: kubectl delete secret {{ cloudera_api_secret.secret_name }} -n {{ cloudera_api_secret.namespace }}
    ignore_errors: true

  - name: create cloudera-api secret
    shell: kubectl create secret generic {{ cloudera_api_secret.secret_name }} -n {{ cloudera_api_secret.namespace }} --from-literal=CLOUDERA_CLUSTER_NAME={{ cloudera_ingestion_cluster_name }} --from-literal=CLOUDERA_URL=http://{{ cloudera_managment_server.hostname }}.{{ domain }}:7180/api/v33 --from-literal=CLOUDERA_USERNAME={{ cloudera_web_ui.cloudera_username }} --from-literal=CLOUDERA_PASSWORD={{ cloudera_web_ui.cloudera_password }}