---
## Create In memory inventory
- hosts: localhost
  become: true
  any_errors_fatal: true
  gather_facts: False
  vars_files:
    - cloudera_environment.yml
  tasks:

  - add_host:
        name: "{{ item.ip}}"
        groups: "{{ item.group }}"
    loop: "{{ server_details }}"


## Run Playbook ##

- hosts:
    - bigdata_postgres1
    - bigdata_cloudera_manager
    - bigdata_worker
    - bigdata_master
    - bigdata_gw
    - bigdata_kafka
    - bigdata_repository
    - bigdata_kafka_master

  become: yes
  gather_facts: no
  tasks:


     - name: Generate SSH key for root user if not present
       user:
         name: root
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
       delegate_to: localhost
       run_once: true

     - name: Set authorized key taken from file
       authorized_key:
         user: zolo
         state: present
         key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

     - name: Set zolo as default user for ssh
       copy:
         dest: /root/.ssh/config
         content: "Host *\n  User zolo\n"
       delegate_to: localhost
       run_once: yes

     - name: Disable ansible password prompts
       replace:
         dest: /deployment/ansible.cfg
         regexp: "pass.*= True"
         replace: "pass = False"
       delegate_to: localhost
       run_once: yes
