## Create In memory inventory
- hosts: localhost
  become: true
  any_errors_fatal: true
  gather_facts: False
  vars_files:
    - cloudera_environment.yml
  tasks:

  - add_host:
        name: "{{ item.ip}}"
        groups: "{{ item.group }}"
    loop: "{{ server_details }}"

## server reboot   ###

- hosts:
    - bigdata_repository
  become: true
  gather_facts: False
  tasks:
    - name: reboot repository server
      reboot:

- hosts:
    - bigdata_postgres1
  become: true
  gather_facts: False
  tasks:
    - name: reboot postgres server
      reboot:


- hosts:
    - bigdata_cloudera_manager
  become: true
  gather_facts: False
  tasks:
    - name: reboot cloudera managment server
      reboot:


- hosts:
    - bigdata_master
  become: true
  gather_facts: False
  tasks:
    - name: reboot master servers
      reboot:


- hosts:
    - bigdata_worker
  become: true
  gather_facts: False
  tasks:
    - name: reboot worker servers
      reboot:


- hosts:
    - bigdata_kafka_master
  become: true
  gather_facts: False
  tasks:
    - name: reboot kafka-master servers
      reboot:


- hosts:
    - bigdata_kafka
  become: true
  gather_facts: False
  tasks:
    - name: reboot kafka servers
      reboot:


- hosts:
    - bigdata_gw
  become: true
  gather_facts: False
  tasks:
    - name: reboot gw \ edge servers
      reboot:


 ### Verify ping to servers after reboot   ###
- hosts:
      - bigdata_postgres1
      - bigdata_cloudera_manager
      - bigdata_worker
      - bigdata_master
      - bigdata_gw
      - bigdata_kafka
      - bigdata_repository
      - bigdata_kafka_master
  become: true
  gather_facts: False
  tasks:          
    - name: Verify that all hosts are reachable after reboot
      ping:

